# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=50)),
                ('website_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roomate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rating', models.DecimalField(choices=[(5.0, '5'), (4.0, '4'), (3.0, '3'), (2.0, '2'), (1.0, '1')], decimal_places=1, max_digits=2)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomaterating.College')),
            ],
        ),
    ]
