# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OverallRating', models.DecimalField(choices=[(5.0, '5'), (4.0, '4'), (3.0, '3'), (2.0, '2'), (1.0, '1')], decimal_places=1, max_digits=2)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomate',
            name='rating',
        ),
        migrations.AddField(
            model_name='comments',
            name='roommate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomaterating.Roomate'),
        ),
    ]
