# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 02:52
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a college name (No numbers or special characters)', regex='^[A-Za-z\\s]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('Overall_Rating', models.DecimalField(choices=[(5.0, '5'), (4.0, '4'), (3.0, '3'), (2.0, '2'), (1.0, '1')], decimal_places=1, max_digits=2)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='roomate',
            name='student_id',
            field=models.CharField(default=0, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a Student ID (No special characters or spaces)', regex='^[A-Za-z0-9]*$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomate',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a first name (No numbers or special characters)', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='roomate',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a last name (No numbers, special characters or spaces)', regex='^[A-Za-z]*$')]),
        ),
        migrations.AlterUniqueTogether(
            name='college',
            unique_together=set([('campus', 'website_link')]),
        ),
        migrations.RemoveField(
            model_name='roomate',
            name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='roomate',
            unique_together=set([('last_name', 'first_name', 'college', 'student_id')]),
        ),
        migrations.AddField(
            model_name='comment',
            name='roomate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomaterating.Roomate'),
        ),
    ]
