# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0002_auto_20171215_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
