# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0004_auto_20171215_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='roommate',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='Bob', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomate',
            name='comments',
            field=models.ManyToManyField(to='roomaterating.Comment'),
        ),
        migrations.AlterField(
            model_name='college',
            name='campus',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Description',
            field=models.TextField(max_length=500),
        ),
    ]
