# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0005_auto_20171215_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomate',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='roomate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roomaterating.Roomate'),
            preserve_default=False,
        ),
    ]
