# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0006_auto_20171215_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='OverallRating',
            new_name='Overall_Rating',
        ),
    ]
