# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0007_auto_20171228_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='campus_img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
