# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0008_college_campus_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='campus_img',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
