# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0009_auto_20171230_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='campus_img',
            new_name='campus_image',
        ),
    ]
