# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0010_auto_20171230_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomate',
            name='first_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='roomate',
            name='last_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
