# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0011_auto_20171230_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomate',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='roomate',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='roomate',
            unique_together=set([('last_name', 'first_name', 'college')]),
        ),
    ]
