# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0012_auto_20171230_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='campus_image',
        ),
        migrations.AlterUniqueTogether(
            name='college',
            unique_together=set([('campus', 'website_link')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('roomate', 'username')]),
        ),
    ]
