# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0013_auto_20171230_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='campus',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([]),
        ),
    ]
