# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 12:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0014_auto_20171230_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='roomate',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='First Name must be All Caps', regex='^[A-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='roomate',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='Last Name must be All Caps', regex='^[A-Z]*$')]),
        ),
    ]
