# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 10:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0016_auto_20171231_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesuggestion',
            name='college',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a college name (No numbers or special characters)', regex='^[A-Za-z\\s]*$')]),
        ),
    ]
