# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0018_auto_20180107_2325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
