# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0020_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomate',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='roomate',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
