# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 00:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0021_auto_20180109_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomate',
            name='student_id',
            field=models.CharField(default='0', max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a Student ID (No special characters or spaces)', regex='^[A-Za-z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='roomate',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a first name (No numbers or special characters)', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='roomate',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a last name (No numbers, special characters or spaces)', regex='^[A-Za-z]*$')]),
        ),
        migrations.AlterUniqueTogether(
            name='roomate',
            unique_together=set([('last_name', 'first_name', 'college', 'student_id')]),
        ),
    ]
