# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 00:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomaterating', '0022_auto_20180109_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomate',
            name='student_id',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_college', message='Please enter a Student ID (No special characters or spaces)', regex='^[A-Za-z0-9]*$')]),
        ),
    ]
